%%%不要全抄%%%
%导入控制点
[x,y,X,Y]=textread("Geotext.txt",'%f %f %f %f');
[m,n]=size(x);
%系数矩阵
A=[ones(m,1),X,Y];
B=[ones(m,1),x,y];
%正多项式系数
Da=((A'*A)^-1)*A'*x;
Db=((A'*A)^-1)*A'*y;
%逆多项式系数
Da_1=((B'*B)^-1)*B'*X;
Db_1=((B'*B)^-1)*B'*Y;
img=imread("待纠正图像.bmp");
%求出源图像角点坐标
[m,n,~]=size(img);
X1=Da_1'*[1;0;0];
X2=Da_1'*[1;0;m];
X3=Da_1'*[1;n;0];
X4=Da_1'*[1;n;m];
Y1=Db_1'*[1;0;0];
Y2=Db_1'*[1;0;m];
Y3=Db_1'*[1;n;0];
Y4=Db_1'*[1;n;m];
X=[X1,X2,X3,X4];
Y=[Y1,Y2,Y3,Y4];
%新图像范围
Xmax=max(X);
Xmin=min(X);
Ymax=max(Y);
Ymin=min(Y);
M=ceil(Ymax-Ymin)+1;
N=ceil(Xmax-Xmin)+1;
